[Http]
Port = 9800

[Postgres]
Username = "postgres"
Password = "xixi@0202"
Database = "atom"
Host = "10.58.144.6"
Port = 30432

[JWT]
SignKey = "helloworld"

[Casdoor]
Endpoint = "http://casdoor.dev.local"
ClientId = "563f7867202ddd5f4c7d"
ClientSecret = "a82051fabd0cd7de87bb793e7feaca5e1159d58c"
OrganizationName = "TestORG"
ApplicationName = "TestAPP"
Certificate = """-----BEGIN CERTIFICATE-----
MIIE3TCCAsWgAwIBAgIDAeJAMA0GCSqGSIb3DQEBCwUAMCgxDjAMBgNVBAoTBWFk
bWluMRYwFAYDVQQDEw1jZXJ0LWJ1aWx0LWluMB4XDTIzMDcyOTA4MTEwOFoXDTQz
MDcyOTA4MTEwOFowKDEOMAwGA1UEChMFYWRtaW4xFjAUBgNVBAMTDWNlcnQtYnVp
bHQtaW4wggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDDPOfTfHMdI0ch
uY7OFnHs4pgyDX4bWPRtpWJhgOMhy1dhT2H2OFVj713me8BJIWORp3koaX+B6Co2
08kHF86u3lW2kzsUAKIXNUg7J2K1nTo4xR7Ypl503roJ/LrNAnwKxAepn3iPaTfn
QY5nP6lUphxwoKEaBUFgvjyifislx4PoWHatSXjrBh97AGtZmrYeILU/4QY8+uxk
IxxVGRiEeOt7LxdHO9hABotI3jDfJQNmzqz5h1Sh7e4lrrXc+8wLlK7eFJ5hOnYU
n7pBypiISw8uxwwFMpzeu7xCt7oDQ8OcXfvgyl8G45biAh3LfjMyPaeW4Myjtun3
uuP5fsMM3PBlTfBlgQQPHWXEQmcxQzNQ/lxgAKAv0alqD/5LJ9SGyJ9MYC9lHx1X
c237IkaoojVPtcljldDEbPrPO3kJnvZ6EoJh56fTIRPKwHsnMG1i9pmHVZeFNNlQ
aGnF2CQJhdlJt+GSZ6YBN24zikD0F3fTEY5ZAb2wJorFk8IBiCeiPKlkLIl6bvCY
Dv/0dbyJBnwc/ioTSXIYNlHIC89E+Yg48dEO12vwrlOftNrOAik/EdNp78kC1OH6
bMXDdPbcmZVszvcMWPsMLfwQ7T5iteFWkSsZn+cOmVyklCtJpUhxv+2JVaCu/XS9
7DGDUoTR77LD6gVOqmERNU1PVO0Q7QIDAQABoxAwDjAMBgNVHRMBAf8EAjAAMA0G
CSqGSIb3DQEBCwUAA4ICAQCksl2UH5iLlBKcljG+5RZWYtre2Pk2tGz2UtwZSaAS
SJhTWfxQIkXeqmjxV7E0WLe4koUaMxRr3B8++/sOMEnQrfH+NnjxRcNV3GyW4Xjl
amv4fGOP44uAeZR1/J/8a9tI0GNRUjA1EkMq2R8+X/+gZIZoeDs/5Eidx5uSDvwM
RtUWZIcsgeuEQbceB6DyaNoYd4RtEBWCyz/wKTT1TvGDPnqKLSE65pryZ3r/X7BP
hpEOTqpm+WWGSVsQMkJRkJhatLtBkIzys32vImxyooijNxuBmwAV6TBAf0AIOOb1
dLoJfrUDN1cMm7n1MQTDTKtjDRgov4Fl47ZI7X3H0eJckGrqSwqXAAg+7qyLOC4u
Xzhp9dIfqiB/L+xbCsTU2Iwmi30m6WKY9s7WS/Uk65n9wAvPiDCUCOwxO4A1KUVJ
fJLRQOEsvSQq9GeDasI3xoPBJbbat6TAoEZA6RPnwpryKaFz8D8pAc8Ycg8UKlRb
H87CHK5/0nIICOjm4PsGwXEbv+SjW3QTPsHBxTEP1RelABbc9bbCBQv5FaPR1rUB
pXfKrWCYvFlRFo3oKolVaJWoubp+8rwgEn3+DarFaCqQT5GApevoRAzEVZ4PHR43
vYJkSdmAYYHmAAvzdajvfXboUVRsxrydGB2Qfr7KMgYkVKEQBFh6wM0+42FXEeYm
5A==
-----END CERTIFICATE-----"""
