// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/auth/modules/auth/controller"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeAuthController(engine fiber.Router, controller *controller.AuthController) {
	basePath := "/"+engine.(*fiber.Group).Prefix
	engine.Post(strings.TrimPrefix("/auths/login", basePath), DataFunc(controller.Login))
}
