// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/auth/modules/auth/controller"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeCallbackController(engine fiber.Router, controller *controller.CallbackController) {
	basePath := "/"+engine.(*fiber.Group).Prefix
	engine.Get(strings.TrimPrefix("/auth/callback/signin", basePath), DataFunc(controller.Signin))
	engine.Get(strings.TrimPrefix("/auth/callback/signup", basePath), DataFunc(controller.Signup))
}
