// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/auth/modules/auth/controller"
	"github.com/atom-apps/auth/modules/auth/dto"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeUserController(engine fiber.Router, controller *controller.UserController) {
	basePath := "/"+engine.(*fiber.Group).Prefix
	engine.Get(strings.TrimPrefix("/auth/user/profile", basePath), DataFunc(controller.Profile))
	engine.Post(strings.TrimPrefix("/auth/user/reset-password", basePath), Func1(controller.ResetPassword, Body[dto.ResetPasswordForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/auth/user/force-reset-password/:uuid", basePath), Func2(controller.ForceResetPassword, String("uuid", PathParamError), Body[dto.ResetPasswordForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/auth/user/:uuid", basePath), Func2(controller.Update, String("uuid", PathParamError), Body[dto.UserForm](BodyParamError)))
}
