// Code generated by the atomctl; DO NOT EDIT.

package routes

import (
	 "strings"

	"github.com/atom-apps/auth/modules/auth/controller"
	"github.com/atom-apps/auth/modules/auth/dto"

	"github.com/gofiber/fiber/v2"
	. "github.com/rogeecn/fen"
)

func routeRoleController(engine fiber.Router, controller *controller.RoleController) {
	basePath := "/"+engine.(*fiber.Group).Prefix
	engine.Put(strings.TrimPrefix("/auth/role/add-users", basePath), Func1(controller.AddUsers, Body[dto.RoleUsersForm](BodyParamError)))
	engine.Put(strings.TrimPrefix("/auth/role/remove-users", basePath), Func1(controller.RemoveUsers, Body[dto.RoleUsersForm](BodyParamError)))
}
